### PR TITLE
JsonSerializable

### PR DESCRIPTION
**Pull request by EgorGruzdev**

### CODE REVIEW

**Comment by garak** [comment]
Thanks for your contribution. There are a couple of issues with this PR:
* it adds a new method, but it doesn't add a test for it
* it contains unrelated features. It would be better to propose a single feeature per PR

**Comment by EgorGruzdev** [comment]
I wanted to issue as an offer, because I encountered this problem when working with the library.
I will try to arrange properly, but I do not have very little experience in this regard.

**Comment by EgorGruzdev** [comment]
Perhaps this method is not needed here, and each for itself inherits it, if it is needed.

**Comment by garak** [comment]
The method can be useful, you just need to:
* add a test for such method
* remove all changes unrelated to new method

thanks

**Comment by EgorGruzdev** [comment]
Look, did I do that?
https://github.com/EgorGruzdev/shortid-php/commit/9b1c81a467bf659f7d6199933d206f0cc48ed75c

**Pull request closed without merging**
